/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef __DRV_EVENT_H__
#define __DRV_EVENT_H__

/* ------------------------ Includes --------------------------------------- */
/* ------------------------ Macros ----------------------------------------- */
// 256 and 4096 are the sizes of the recv buffers on OOBHUB side for these respective events.
#define NV_DRV_EVENT_TEXT_STRING_MAX        (256 - sizeof(struct drvEventRecord))
#define NV_DRV_EVENT_DATA_DUMP_MAX          (4096 - NV_DRV_EVENT_TEXT_STRING_MAX - sizeof(struct drvEventRecord))

#define NV_RIST_TELEMETRY_GPU_UUID_MAX_LENGTH           64
#define NV_RIST_TELEMETRY_APP_VERSION_MAX_LENGTH        16

#define NV_STARTUP_EVENT_CAPS_REQ_SUPPORTED             0:0
#define NV_STARTUP_EVENT_CAPS_REQ_SUPPORTED_NO          0x0
#define NV_STARTUP_EVENT_CAPS_REQ_SUPPORTED_YES         0x1
#define NV_STARTUP_EVENT_CAPS_ASYNC_EVENT_SUPPORTED     1:1
#define NV_STARTUP_EVENT_CAPS_ASYNC_EVENT_SUPPORTED_NO  0x0
#define NV_STARTUP_EVENT_CAPS_ASYNC_EVENT_SUPPORTED_YES 0x1

#define NV_DRV_EVENT_FLAGS_TRUNCATED                    0:0
#define NV_DRV_EVENT_FLAGS_TRUNCATED_NO                   0
#define NV_DRV_EVENT_FLAGS_TRUNCATED_YES                  1

#define NSM_TYPE_INTERNAL_EVENT_STARTUP                 0x00
#define NSM_TYPE_INTERNAL_EVENT_SHUTDOWN                0x01
#define NSM_TYPE_INTERNAL_DRIVER_INIT                   0x02
#define NSM_TYPE_INTERNAL_DRIVER_MESSAGE                0x03
#define NSM_TYPE_INTERNAL_RESET_REQUIRED                0x04
#define NSM_TYPE_INTERNAL_DRIVER_VERBOSE_MESSAGE        0x05
#define NSM_TYPE_INTERNAL_CPER                          0x06
#define NSM_TYPE_INTERNAL_EVENT_STARTUP_V2              0x07
#define NSM_TYPE_INTERNAL_EVENT_SHUTDOWN_V2             0x08
#define NSM_TYPE_INTERNAL_RIST_TELEMETRY                0x09

/* ------------------------ Data types ------------------------------------- */

/**
 * StartupEventPayload
 * Generated by the driver StateInit sequence.
 **/

typedef struct {
    NvU8 queueDepth;    // receive_queue_depth in PMU
    NvU8 basicCapabilities;
    NvU16 reserved;
} StartupEventPayload;

/**
 * drvEventRecord
 *
 * An event is generated when a driver error message (Xid) has been issued.
 * This is the layout of this event's payload.
 *
 * If dbgDumpOffset is non-zero:
 *     - The flexible array payload has two sections: the XID message string (like in v1), and a debug dump
 *     - The dbgDumpOffset stores the offset of the second section (debug dump) relative to start of the record.
 **/
typedef struct drvEventRecord
{
    NvU8    flags;            //!< Bit 0:    Message text string truncated
                              //!< Bits 7-1: Reserved
    NvU8    dbgDumpOffset;    //!< Starting offset of debug dump relative to start of record
    NvU8    reserved[2];      //!< Reserved, MBZ
    NvU32   reason;           //!< Driver message type (Xid)
    NvU32   seqNumber;        //!< Sequence number
    NvU32   timestampLo;      //!< Epoch ns timestamp low 32 bits
    NvU32   timestampHi;      //!< Epoch ns timestamp high 32 bits
    /*
     * Some Windows builds may include this file, and older Microsoft
     * compilers won't accept a zero size array in this context:
     * "C4200 nonstandard extension used: zero-sized array in struct/union",
     * despite this being a legitimate C99.
     */
    NvU8    text[];         //<! non-terminated, up to NV_DRV_EVENT_TEXT_STRING_MAX
} drvEventRecord;

/**
 * An event is generated when the GPU is marked or unmarked for reset.
 * This is the layout of this event's payload.
 **/
typedef struct drvResetRequired
{
    NvU8    set;        //!< FALSE: unmark for reset
                        //!< TRUE:  mark for reset
} drvResetRequired;

/**
 * @brief NSM_TYPE_INTERNAL_CPER CPER event payload
 *
 * This is the payload for the CPER event.
 */
typedef struct {
    NvU32 reserved;     //!< Reserved
    NvU8  data[];       //!< Variable-length CPER record
} CperEventPayload;

/**
 * @brief NSM_TYPE_INTERNAL_RIST_TELEMETRY RIST telemetry event payload
 *
 * This is the payload for the RIST telemetry event.
 */
#pragma pack(1)
typedef struct {
    NvU8   gpuUuid[NV_RIST_TELEMETRY_GPU_UUID_MAX_LENGTH];       //!< GPU UUID
    NvU64  timestamp;                                            //!< Timestamp (ns since epoch)
    NvU8   appVersion[NV_RIST_TELEMETRY_APP_VERSION_MAX_LENGTH]; //!< Application version string
    NvBool bSuccess;                                             //!< Result of the operation (NV_TRUE for success, NV_FALSE for failure)
    NvU64  statusCode;                                           //!< Status code
    NvTemp maxTemp;                                              //!< Maximum temperature observed during RIST (Celsius)
    NvTemp avgTemp;                                              //!< Average temperature observed during RIST (Celsius)
} RistTelemetryEventPayload;
#pragma pack()

#endif /* __DRV_EVENT_H__ */
