/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef _NVLINK_EVENT_CTX_DEFS_H_
#define _NVLINK_EVENT_CTX_DEFS_H_

#include "events/gpu/gpu_event_ctx_defs.h"
#include "nvtypes.h"

#define NVLINK_ALI_TRAINING_FAILURE_DATA_VERSION_MAJOR 1
#define NVLINK_ALI_TRAINING_FAILURE_DATA_VERSION_MINOR 0
#define NVLINK_ALI_TRAINING_FAILURE_DATA_VERSION       \
    ((NVLINK_ALI_TRAINING_FAILURE_DATA_VERSION_MINOR) | \
     (NVLINK_ALI_TRAINING_FAILURE_DATA_VERSION_MAJOR << 8))
#define NVLINK_ALI_TRAINING_FAILURE_MAX_ENTRIES        36
#define NVLINK_ALI_TRAINING_FAILURE_MAX_DEBUG_WORDS    7

typedef NvU16 NVLINK_EVENT_CTX_TYPE;
enum
{
    NVLINK_EVENT_CTX_TYPES_BASE = GPU_OPERATIONAL_EVENT_CTX_TYPES_GPU_NVLINK_BASE,
    NVLINK_EVENT_CTX_TYPE_ALI_TRAINING_FAILURE_DATA, // 0xA301
    NVLINK_EVENT_CTX_TYPE_MSE_ERROR_DATA,            // 0xA302
    NVLINK_EVENT_CTX_TYPE_SW_LINK_DOWN_ERROR_DATA,   // 0xA303
};

typedef struct NVLINK_ALI_TRAINING_FAILURE_ENTRY
{
    NvU8  linkId;
    NvU8  reserved[3];
    EVENT_CTX_FLEXIBLE_ARRAY_MEMBER(NvU32, debugData, NVLINK_ALI_TRAINING_FAILURE_MAX_DEBUG_WORDS)
} NVLINK_ALI_TRAINING_FAILURE_ENTRY;

typedef struct NVLINK_ALI_TRAINING_FAILURE_DATA
{
    NvU8 entryCount;
    NvU8 debugDataCount;
    NvU8 reserved[2];
    NVLINK_ALI_TRAINING_FAILURE_ENTRY linkErrorInfo[NVLINK_ALI_TRAINING_FAILURE_MAX_ENTRIES];
} NVLINK_ALI_TRAINING_FAILURE_DATA;

#define NVLINK_ALI_TRAINING_FAILURE_LEGACY_DATA_VERSION_MAJOR 1
#define NVLINK_ALI_TRAINING_FAILURE_LEGACY_DATA_VERSION_MINOR 0
#define NVLINK_ALI_TRAINING_FAILURE_LEGACY_DATA_VERSION       \
    ((NVLINK_ALI_TRAINING_FAILURE_LEGACY_DATA_VERSION_MINOR) | \
     (NVLINK_ALI_TRAINING_FAILURE_LEGACY_DATA_VERSION_MAJOR << 8))

typedef struct NVLINK_ALI_TRAINING_FAILURE_LEGACY_DATA
{
    NvU8  entryCount;
    NvU8  debugDataCount;
    NvU8  reserved[2];
    NvU32 legacyXidCode;
    NvU64 legacyLinkMask;
    NVLINK_ALI_TRAINING_FAILURE_ENTRY linkErrorInfo[NVLINK_ALI_TRAINING_FAILURE_MAX_ENTRIES];
} NVLINK_ALI_TRAINING_FAILURE_LEGACY_DATA;

#define NVLINK_MSE_ERROR_DATA_VERSION_MAJOR 1
#define NVLINK_MSE_ERROR_DATA_VERSION_MINOR 0
#define NVLINK_MSE_ERROR_DATA_VERSION       \
    ((NVLINK_MSE_ERROR_DATA_VERSION_MINOR) | \
     (NVLINK_MSE_ERROR_DATA_VERSION_MAJOR << 8))
#define NVLINK_MSE_ERROR_DEBUG_WORDS        4

typedef struct NVLINK_MSE_ERROR_DATA
{
    NvU32 errorStatus;
    NvU32 debugData[NVLINK_MSE_ERROR_DEBUG_WORDS];
} NVLINK_MSE_ERROR_DATA;

#define NVLINK_MSE_ERROR_LEGACY_DATA_VERSION_MAJOR 1
#define NVLINK_MSE_ERROR_LEGACY_DATA_VERSION_MINOR 0
#define NVLINK_MSE_ERROR_LEGACY_DATA_VERSION       \
    ((NVLINK_MSE_ERROR_LEGACY_DATA_VERSION_MINOR) | \
     (NVLINK_MSE_ERROR_LEGACY_DATA_VERSION_MAJOR << 8))

typedef NvU32 NVLINK_MSE_LEGACY_XID_ERROR_NAME;
enum
{
    NVLINK_MSE_LEGACY_XID_ERROR_NAME_WATCHDOG = 0,
    NVLINK_MSE_LEGACY_XID_ERROR_NAME_DEGRADED = 1,
};

typedef struct NVLINK_MSE_ERROR_LEGACY_DATA
{
    NVLINK_MSE_LEGACY_XID_ERROR_NAME legacyXidErrorName;
    NvBool bLegacyFatal;
    NvBool bLegacyXContain;
    NvBool bLegacyInjected;
    NvS32 legacyLinkId;
    NvU32 legacyIntrInfo;
    NvU32 legacyErrorStatus;
    NvU32 legacyXidCode;
    NvU32 debugData[NVLINK_MSE_ERROR_DEBUG_WORDS];
} NVLINK_MSE_ERROR_LEGACY_DATA;

#define NVLINK_SW_LINK_DOWN_ERROR_DATA_VERSION_MAJOR 1
#define NVLINK_SW_LINK_DOWN_ERROR_DATA_VERSION_MINOR 0
#define NVLINK_SW_LINK_DOWN_ERROR_DATA_VERSION       \
    ((NVLINK_SW_LINK_DOWN_ERROR_DATA_VERSION_MINOR) | \
     (NVLINK_SW_LINK_DOWN_ERROR_DATA_VERSION_MAJOR << 8))
#define NVLINK_SW_LINK_DOWN_ERROR_DEBUG_WORDS        8

typedef struct NVLINK_SW_LINK_DOWN_ERROR_DATA
{
    NvU8  linkId;
    NvU8  reserved[3];
    NvU32 debugData[NVLINK_SW_LINK_DOWN_ERROR_DEBUG_WORDS];
} NVLINK_SW_LINK_DOWN_ERROR_DATA;

#define NVLINK_SW_LINK_DOWN_ERROR_LEGACY_DATA_VERSION_MAJOR 1
#define NVLINK_SW_LINK_DOWN_ERROR_LEGACY_DATA_VERSION_MINOR 0
#define NVLINK_SW_LINK_DOWN_ERROR_LEGACY_DATA_VERSION       \
    ((NVLINK_SW_LINK_DOWN_ERROR_LEGACY_DATA_VERSION_MINOR) | \
     (NVLINK_SW_LINK_DOWN_ERROR_LEGACY_DATA_VERSION_MAJOR << 8))

typedef struct NVLINK_SW_LINK_DOWN_ERROR_LEGACY_DATA
{
    NvBool bLegacyFatal;
    NvBool bLegacyXContain;
    NvBool bLegacyInjected;
    NvU32 legacyXidCode;
    NvU8  linkId;
    NvU8  reserved[3];
} NVLINK_SW_LINK_DOWN_ERROR_LEGACY_DATA;

#endif // _NVLINK_EVENT_CTX_DEFS_H_
