dnl # commit 67dd1a36334ffce82bebeb2d633e152aa436d370
dnl # drm/amdgpu: Add AMDGPU_CHUNK_ID_SCHEDULED_DEPENDENCIES
AC_DEFUN([AC_AMDGPU_CHUNK_ID_SCHEDULED_DEPENDENCIES], [
	AC_KERNEL_DO_BACKGROUND([
		AC_KERNEL_TRY_COMPILE([
			#include <drm/amdgpu_drm.h>
		], [
			#ifndef AMDGPU_CHUNK_ID_SCHEDULED_DEPENDENCIES
			#error AMDGPU_CHUNK_ID_SCHEDULED_DEPENDENCIES not #defined
			#endif
		], [
			AC_DEFINE(HAVE_AMDGPU_CHUNK_ID_SCHEDULED_DEPENDENCIES, 1,
				[whether AMDGPU_CHUNK_ID_SCHEDULED_DEPENDENCIES is defined])
		])
	])
])
