dkmstree := drivers/gpu/drm/amd/dkms
srctree := $(subst /$(dkmstree),,$(realpath $(dir $(lastword $(MAKEFILE_LIST)))))

all: config clean

config: force
	@( \
		cd $(srctree)/$(dkmstree); \
		./autogen.sh; \
		./configure \
			--enable-linux-builtin \
			--with-linux=$(srctree) \
	)

clean: force
	@( \
		cd $(srctree)/$(dkmstree); \
		rm -f aclocal.m4 config.* configure config/*.in* \
	)

.PHONY: all force
