/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef _GPU_EVENT_DEFS_H_
#define _GPU_EVENT_DEFS_H_

#include "events/event_defs.h"
#include "nvtypes.h"

#define GPU_OPERATIONAL_EVENT_MIG_ATTRIBUTION_NONE 0xFFU

typedef NvU16 GPU_OPERATIONAL_EVENT_CATEGORY;
enum
{
    GPU_OPERATIONAL_EVENT_CATEGORY_TIMEOUT                = 0x0001,
    GPU_OPERATIONAL_EVENT_CATEGORY_MEMORY_INTEGRITY_ERROR = 0x0002,
    GPU_OPERATIONAL_EVENT_CATEGORY_INTERCONNECT_ERROR     = 0x0003,
    GPU_OPERATIONAL_EVENT_CATEGORY_CORRUPTION_DETECTED    = 0x0004,
    GPU_OPERATIONAL_EVENT_CATEGORY_SECURITY_ERROR         = 0x0005,
    GPU_OPERATIONAL_EVENT_CATEGORY_POWER_ERROR            = 0x0006,
    GPU_OPERATIONAL_EVENT_CATEGORY_THERMAL_ERROR          = 0x0007,
    GPU_OPERATIONAL_EVENT_CATEGORY_FIRMWARE_FAULT         = 0x0008,
    GPU_OPERATIONAL_EVENT_CATEGORY_ENGINE_ERROR           = 0x0009,
    GPU_OPERATIONAL_EVENT_CATEGORY_RESOURCE_EXHAUSTED     = 0x000A,
    GPU_OPERATIONAL_EVENT_CATEGORY_TRANSLATION_FAULT      = 0x000B,
    GPU_OPERATIONAL_EVENT_CATEGORY_UNCLASSIFIED_ERROR     = 0x7FFF,
    GPU_OPERATIONAL_EVENT_CATEGORY_INITIALIZATION         = 0x8000,
    GPU_OPERATIONAL_EVENT_CATEGORY_SHUTDOWN               = 0x8001,
    GPU_OPERATIONAL_EVENT_CATEGORY_STATE_CHANGED          = 0x8002,
    GPU_OPERATIONAL_EVENT_CATEGORY_CONFIG_CHANGED         = 0x8003,
    GPU_OPERATIONAL_EVENT_CATEGORY_RESOURCE_RETIREMENT    = 0x8004,
    GPU_OPERATIONAL_EVENT_CATEGORY_RESOURCE_THRESHOLD     = 0x8005,
    GPU_OPERATIONAL_EVENT_CATEGORY_TELEMETRY              = 0xFFFE,
    GPU_OPERATIONAL_EVENT_CATEGORY_DEBUG                  = 0xFFFF,
};

typedef NvU8 GPU_OPERATIONAL_EVENT_SCOPE;
enum
{
    GPU_OPERATIONAL_EVENT_SCOPE_SYSTEM           = 0,
    GPU_OPERATIONAL_EVENT_SCOPE_DEVICE           = 1,
    GPU_OPERATIONAL_EVENT_SCOPE_GPU_INSTANCE     = 2,
    GPU_OPERATIONAL_EVENT_SCOPE_COMPUTE_INSTANCE = 3,
    GPU_OPERATIONAL_EVENT_SCOPE_ENGINE           = 4,
};

typedef NvU8 GPU_OPERATIONAL_EVENT_ORIGINATOR;
enum
{
    GPU_OPERATIONAL_EVENT_ORIGINATOR_NONE      = 0,
    GPU_OPERATIONAL_EVENT_ORIGINATOR_PF_GSP_FW = 2,
    GPU_OPERATIONAL_EVENT_ORIGINATOR_VF_GSP_FW = 3,
    GPU_OPERATIONAL_EVENT_ORIGINATOR_PF_DRIVER = 4,
    GPU_OPERATIONAL_EVENT_ORIGINATOR_VF_DRIVER = 5,
};

typedef NvU8 GPU_OPERATIONAL_EVENT_REPORTING_SOURCE;
enum
{
    GPU_OPERATIONAL_EVENT_REPORTING_SOURCE_SW_CHECK      = 0,
    GPU_OPERATIONAL_EVENT_REPORTING_SOURCE_INTERRUPT     = 1,
    GPU_OPERATIONAL_EVENT_REPORTING_SOURCE_FW_FAULT      = 2,
    GPU_OPERATIONAL_EVENT_REPORTING_SOURCE_TIMEOUT       = 3,
    GPU_OPERATIONAL_EVENT_REPORTING_SOURCE_DRIVER_CLIENT = 4,
    GPU_OPERATIONAL_EVENT_REPORTING_SOURCE_UNKNOWN       = 0xFF,
};

typedef NvU8 GPU_OPERATIONAL_EVENT_LOG_LEVEL;
enum
{
    GPU_OPERATIONAL_EVENT_LOG_LEVEL_ALL        = 0,
    GPU_OPERATIONAL_EVENT_LOG_LEVEL_TELEMETRY  = 10,
    GPU_OPERATIONAL_EVENT_LOG_LEVEL_DIAGNOSTIC = 20,
    GPU_OPERATIONAL_EVENT_LOG_LEVEL_NOTICE     = 30,
    GPU_OPERATIONAL_EVENT_LOG_LEVEL_WARNING    = 40,
    GPU_OPERATIONAL_EVENT_LOG_LEVEL_ERROR      = 50,
};

typedef NvU16 GPU_OP_EVENT_CODE;
enum
{
    GPU_OP_EVENT_CODE_DRIVER_INIT = 0x0001U,
    GPU_OP_EVENT_CODE_C2C_CONTAINMENT = 0x0002U,
};

#endif // _GPU_EVENT_DEFS_H_
