/************************************************************************************
 * ################### THIS FILE IS AUTOGENERATED. DO NOT EDIT. ################### *
 ***********************************************************************************/


#ifdef __VGPU_ALIAS_PGPU_LIST__
static inline void _get_chip_id_for_alias_pgpu(NvU32 *dev_id, NvU32 *subdev_id)
{
    struct vgpu_alias_details {
        NvU32 alias_devid;
        NvU32 alias_subdevid;
        NvU32 devid;
        NvU32 subdevid;
    } vgpu_aliases[] = {
        { 0x20B5, 0x1642, 0x20B5, 0x1533 },
        { 0x20B8, 0x1581, 0x20B5, 0x1533 },
        { 0x20B9, 0x157F, 0x20B7, 0x1532 },
        { 0x2330, 0x16C0, 0x2330, 0x16C1 },
    };

    for (NvU32 i = 0; i < (sizeof(vgpu_aliases) / sizeof(struct vgpu_alias_details)); ++i) {
        if ((*dev_id == vgpu_aliases[i].alias_devid) && (*subdev_id == vgpu_aliases[i].alias_subdevid)) {
            *dev_id = vgpu_aliases[i].devid;
            *subdev_id = vgpu_aliases[i].subdevid;
            break;
        }
    }

    return;
}
#endif //__VGPU_ALIAS_PGPU_LIST__


