/*
 * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef __gb100_dev_oob_pri_h__
#define __gb100_dev_oob_pri_h__

#define NV_POOBHUB_PEREGRINE_MNOC_RX_FIFO_DATA(i)                             (0x008a9e00+(i)*8) /* -W-4A */
#define NV_POOBHUB_PEREGRINE_MNOC_RX_FIFO_DATA__SIZE_1                                         9 /*       */
#define NV_POOBHUB_PEREGRINE_MNOC_RX_FIFO_DATA_WDATA                                        31:0 /* -WXVF */

#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK(i)      (0x008a9f80+(i)*12) /* RW-4A */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK__SIZE_1                   4 /*       */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_READ_PROTECTION         3:0 /* RWIVF */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED 0xf /* RWI-V */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_WRITE_PROTECTION        7:4 /* RWIVF */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED 0xf /* RWI-V */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_READ_VIOLATION          8:8 /* RWIVF */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR 0x1 /* RWI-V */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON 0x0 /* RW--V */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_WRITE_VIOLATION         9:9 /* RWIVF */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR 0x1 /* RWI-V */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON 0x0 /* RW--V */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL   10:10 /* RWIVF */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED 0x1 /* RW--V */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED 0x0 /* RWI-V */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL  11:11 /* RWIVF */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED 0x1 /* RWI-V */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED 0x0 /* RW--V */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_SOURCE_ENABLE         31:12 /* RWIVF */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_SOURCE_ENABLE_ALL_DISABLED 0x00000 /* RWI-V */
#define NV_POOBHUB_PEREGRINE_MNOC_RECEIVEMBOX_PRIV_LEVEL_MASK_SOURCE_ENABLE_ALL_ENABLED 0xfffff /* RW--V */

#define NV_POOBHUB_RCV_INDIRECT_CMS2_MEM_RD_ADDR                               0x008aa374 /* RW-4R */
#define NV_POOBHUB_RCV_INDIRECT_CMS2_MEM_RD_DATA                               0x008aa378 /* R--4R */

#endif // __gb100_dev_oob_pri_h__
