/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef _EVENT_DEFS_H_
#define _EVENT_DEFS_H_

#include "nvtypes.h"

#define OPERATIONAL_EVENT_MODULE_SIGNATURE_LEN 16U

typedef NvU8 OPERATIONAL_EVENT_SEVERITY;
enum
{
    OPERATIONAL_EVENT_SEVERITY_ALL           = 0U,
    OPERATIONAL_EVENT_SEVERITY_INFORMATIONAL = 10U,
    OPERATIONAL_EVENT_SEVERITY_CORRECTED     = 20U,
    OPERATIONAL_EVENT_SEVERITY_RECOVERABLE   = 30U,
    OPERATIONAL_EVENT_SEVERITY_FATAL         = 40U,
};

// Per-event log level. Domain-specific constants (e.g.
// GPU_OPERATIONAL_EVENT_LOG_LEVEL_*) live in domain headers. This is a
// short-term carrier until per-sink serializers can assign log level
// per output.
typedef NvU8 OPERATIONAL_EVENT_LOG_LEVEL;

typedef NvU8 OPERATIONAL_EVENT_ATTRIBUTES;
#define OPERATIONAL_EVENT_ATTR_UNCONTAINED              0:0
#define OPERATIONAL_EVENT_ATTR_UNCONTAINED_FALSE        0x00000000U
#define OPERATIONAL_EVENT_ATTR_UNCONTAINED_TRUE         0x00000001U
#define OPERATIONAL_EVENT_ATTR_LATENT                   1:1
#define OPERATIONAL_EVENT_ATTR_LATENT_FALSE             0x00000000U
#define OPERATIONAL_EVENT_ATTR_LATENT_TRUE              0x00000001U
#define OPERATIONAL_EVENT_ATTR_PROPAGATED               2:2
#define OPERATIONAL_EVENT_ATTR_PROPAGATED_FALSE         0x00000000U
#define OPERATIONAL_EVENT_ATTR_PROPAGATED_TRUE          0x00000001U
#define OPERATIONAL_EVENT_ATTR_COMPONENT_RESET          3:3
#define OPERATIONAL_EVENT_ATTR_COMPONENT_RESET_FALSE    0x00000000U
#define OPERATIONAL_EVENT_ATTR_COMPONENT_RESET_TRUE     0x00000001U
#define OPERATIONAL_EVENT_ATTR_THRESHOLD_EXCEEDED       4:4
#define OPERATIONAL_EVENT_ATTR_THRESHOLD_EXCEEDED_FALSE 0x00000000U
#define OPERATIONAL_EVENT_ATTR_THRESHOLD_EXCEEDED_TRUE  0x00000001U
#define OPERATIONAL_EVENT_ATTR_PRIMARY                  5:5
#define OPERATIONAL_EVENT_ATTR_PRIMARY_FALSE            0x00000000U
#define OPERATIONAL_EVENT_ATTR_PRIMARY_TRUE             0x00000001U
#define OPERATIONAL_EVENT_ATTR_OVERFLOW                 6:6
#define OPERATIONAL_EVENT_ATTR_OVERFLOW_FALSE           0x00000000U
#define OPERATIONAL_EVENT_ATTR_OVERFLOW_TRUE            0x00000001U
#define OPERATIONAL_EVENT_ATTR_RESERVED                 7:7

typedef NvU8 OPERATIONAL_EVENT_GROUP_ATTRIBUTES;
#define OPERATIONAL_EVENT_GROUP_ATTR_RECOVERED       0:0
#define OPERATIONAL_EVENT_GROUP_ATTR_RECOVERED_FALSE 0x00000000U
#define OPERATIONAL_EVENT_GROUP_ATTR_RECOVERED_TRUE  0x00000001U
#define OPERATIONAL_EVENT_GROUP_ATTR_PREVERR         1:1
#define OPERATIONAL_EVENT_GROUP_ATTR_PREVERR_FALSE   0x00000000U
#define OPERATIONAL_EVENT_GROUP_ATTR_PREVERR_TRUE    0x00000001U
#define OPERATIONAL_EVENT_GROUP_ATTR_SIMULATED       2:2
#define OPERATIONAL_EVENT_GROUP_ATTR_SIMULATED_FALSE 0x00000000U
#define OPERATIONAL_EVENT_GROUP_ATTR_SIMULATED_TRUE  0x00000001U
#define OPERATIONAL_EVENT_GROUP_ATTR_RESERVED        7:3

#endif // _EVENT_DEFS_H_
